on: pull_request
name: Pull Request

jobs:
  test:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.10.0
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
